-- Migration: Add RECENTLY_VIEWED table
-- Run this manually on MySQL/production environments.
-- For H2/local dev, Hibernate hbm2ddl.auto=update handles this automatically.

CREATE TABLE IF NOT EXISTS RECENTLY_VIEWED (
    RECENTLY_VIEWED_ID  BIGINT          NOT NULL AUTO_INCREMENT,
    PRODUCT_ID          BIGINT          NOT NULL,
    CUSTOMER_ID         BIGINT          NULL,
    SESSION_ID          VARCHAR(255)    NULL,
    VIEWED_AT           DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RECENTLY_VIEWED_ID),
    CONSTRAINT FK_RV_PRODUCT  FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT (PRODUCT_ID),
    CONSTRAINT FK_RV_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMERS_ID),
    INDEX IDX_RV_CUSTOMER (CUSTOMER_ID, VIEWED_AT DESC),
    INDEX IDX_RV_SESSION  (SESSION_ID,  VIEWED_AT DESC)
);

-- Sequencer row required by Hibernate TABLE strategy
INSERT IGNORE INTO SM_SEQUENCER (SEQ_NAME, SEQ_COUNT)
VALUES ('RECENTLY_VIEWED_SEQ_NEXT_VAL', 1);
