package com.salesmanager.drools.rules;

import com.salesmanager.core.business.modules.integration.shipping.impl.ShippingInputParameters;

global com.salesmanager.core.business.modules.integration.shipping.impl.DecisionResponse decision;

dialect  "mvel"

rule "40 kilometers or less"
    when
        ShippingInputParameters(distance <= 40)
    then
        decision.setCustomPrice("75");
end

rule "80 kilometers or less"
    when
        ShippingInputParameters(distance <=80)
    then
        decision.setCustomPrice("120");
end
