package com.salesmanager.drools.rules;

import com.salesmanager.core.business.modules.order.total.OrderTotalInputParameters;

global com.salesmanager.core.business.modules.order.total.OrderTotalResponse total;

dialect  "mvel"


rule "Bam0520"
    when
        OrderTotalInputParameters(promoCode == 'Test1234')
        OrderTotalInputParameters(date < "31-Oct-2025")
    then
        total.setDiscount(0.10);
end
