name: Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy (default: latest)'
        required: false
        default: 'latest'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy shopizer
        run: kubectl rollout restart deployment/shopizer -n shopizer
